/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

void configureLED(uint32_t* port) {
	// blue led at pb7

	//mode
	*port &= ~(0x3 << 14);
	*port |= (0x1 << 14);

	//output type -> out
	*(port + 1) &= ~(0x1 << 7);

	//out speed -> medium
	*(port + 2) &= ~(0x3 << 14);
	*(port + 2) |= (0x1 << 14);

	//pull
	*(port + 3) &= ~(0x3 << 14);
}

void turnOn(uint32_t* port) {
	volatile uint32_t* blue = port + 5;
	*blue |= (0x1 << 7);

}

void turnOff(uint32_t* port){
	volatile uint32_t* blue = port + 5;
	*blue &= ~(0x1 << 7);

}

void configureButton(uint32_t* port){

	// mode
	// 00 input mode
	*port &= ~(0x3 << 26);
	*(port + 3) |= (0x2 << 26);

}

void configureNVIC(){
	volatile uint32_t* setEnable = (uint32_t*) 0xE000E104;
	volatile uint32_t* priority = (uint32_t*) 0xE000E428;

	*setEnable |= (1 << 8);
	*priority = (0x10 << 24);
}



volatile uint8_t pressed = 0;
volatile uint8_t isOn = 0;

void EXTI15_10_IRQHandler(void) {
	volatile uint32_t* pending = (uint32_t*) (0x40010400 + 0x14);
	if (*pending & (1 << 13)) {
		pressed = 1;
		*pending = (1 << 13);
	}
}

int main(void)
{
	//configure clock
	volatile uint32_t* clock = (uint32_t*) (0x40021000 + 0x4C);
	*clock |= 0x6; // only turn on clock for gpio b, c

	//configure syscfg
	volatile uint32_t* apb2Clock = (uint32_t*) (0x40021000 + 0x60);
	*apb2Clock |= 0x1;

	// wire the exti
	volatile uint32_t* sys = (uint32_t*) (0x40010000 + 0x14);
	*sys |= (0x2 << 4); //config exti13

	//mexti mask
	volatile uint32_t* extiMask = (uint32_t*) (0x40010400);
	*extiMask |= (0x1 << 13);

	volatile uint32_t* extiEnable = (uint32_t*) (0x40010400 + 0x08);
	*extiEnable |= (1 << 13); // disable rising edge
	volatile uint32_t* extiDisable = (uint32_t*) (0x40010400 + 0x0C);
	*extiDisable &= ~(1 << 13);


	uint32_t* portb = (uint32_t*) 0x48000400;
	configureLED(portb);

	uint32_t* portc = (uint32_t*) 0x48000800;
	configureButton(portc);

	configureNVIC();

	while(1){
		if (pressed){
			if (isOn){
				turnOff(portb);
				isOn = 0;
			}
			else{
				turnOn(portb);
				isOn = 1;
			}
			pressed = 0;

		}

	}
}
